import { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import { deleteImage, getAllImageId, getImageById } from '../src/api/images';

import { ImageType } from '.';
import styles from '../styles/Post.module.scss';
import Button from '../src/uikit/Button';
import { useRouter } from 'next/router';

interface Props {
  image: ImageType;
  notFound: boolean;
}

const Post: NextPage<Props> = ({ image, notFound }) => {
  const { title, url, description, createdAt, id } = image;

  const router = useRouter();
  const date = new Date(createdAt);

  const handleDelete = async () => {
    await deleteImage(id);
    router.push('/');
  };

  if (notFound) {
    return <div className={styles.notFound}>Not Found</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.header}>
            <h3>{title}</h3>
            <Button onClick={handleDelete} label="delete" />
          </div>
          <div className={styles.image}>
            <div>
              <Image
                src={url}
                priority
                alt="Your photo"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
          <p>{`Post created: ${date.getDate()}/${date.getMonth()}/${date.getFullYear()}`}</p>
          {description && <p>Description: {description}</p>}
        </div>
      </main>
    </div>
  );
};

export default Post;

export async function getStaticPaths() {
  try {
    let ids = [Number];
    await getAllImageId()
      .then((response) => (ids = response))
      .catch((err) => console.log('ERROR'));
    const paths = ids.map((id) => ({
      params: {
        id: id.toString()
      }
    }));
    return {
      paths,
      fallback: 'blocking'
    };
  } catch (e) {
    return { paths: [{}], fallback: 'blocking' };
  }
}

export async function getStaticProps({ params }: any) {
  let image: ImageType | {} = {};
  let notFound = false;
  await getImageById(params.id)
    .then((response) => (image = response))
    .catch((err) => (notFound = true));
  return { props: { image, notFound } };
}
