import { ChangeEvent, useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import AddImageForm from '../src/components/AddImageForm';
import { getImages } from '../src/api/images';

export interface ImageType {
  title: string;
  id: number;
  url: string;
  description: string | null;
  liked: boolean;
  createdAt: string;
}

const Home: NextPage = () => {
  const [images, setImages] = useState<ImageType[]>([]);

  useEffect(() => {
    getImages().then((images: []) => {
      setImages(images);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AddImageForm />
        <div>
          {images?.length !== 0 &&
            images.map((image) => (
              <Image src={image.url} alt="img" width={200} height={200} />
            ))}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
