import { ChangeEvent, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AddImageForm from '../src/components/AddImageForm';

export interface ImageType {
  title: string;
  id: number;
  path: string;
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AddImageForm />
        <div>hello</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
